models:
  - name: bert_base_squad1_1
    launchers:
      - framework: dlsdk
        device: cpu
        batch: 1
        adapter:
            type: bert_question_answering
            start_token_logits_output: "unstack/Squeeze_"
            end_token_logits_output: "unstack/Split.1"
        mo_params:
            data_type: FP32
            input: input_ids_1,input_mask_1,segment_ids_1
            input_shape: "[1,384], [1,384], [1,384]"
            output: unstack/Squeeze_,unstack/Split.1
        mo_flags:
            - disable_nhwc_to_nchw
        inputs:
          - name: "input_ids_1"
            type: INPUT
            value: "input_ids"
            precision: I32
          - name: "input_mask_1"
            type: INPUT
            value: 'input_mask'
          - name: "segment_ids_1"
            type: INPUT
            value: 'segment_ids'
            precision: I32

    datasets:
      - name: squad
        data_source: <PATH_TO_DATASET>/squad1.1/
        annotation: <PATH_TO_DATASET>/squad.pickle
        reader:
            type: annotation_features_extractor
            features:
                - input_ids
                - input_mask
                - segment_ids
        postprocessing:
                - type: extract_answers_tokens
                  max_answer: 30
                  n_best_size: 20
        metrics:
            - name: 'F1'
              type: 'f1'
              reference: 88.57
              threshold: 0.01

            - name: 'EM'
              type: 'exact_match'
              reference: 81.25
              threshold: 0.01
