models:
  - name: mask_rcnn_resnet50_atrous_coco

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        adapter:
          type: mask_rcnn
          detection_out: reshape_do_2d
          raw_masks_out: masks
        inputs:
          - name: image_info
            type: CONST_INPUT
            value: [[800, 1365, 1]]
    datasets:
      - name: ms_coco_mask_rcnn_short_91_classes
        annotation_conversion:
          converter: mscoco_mask_rcnn
          annotation_file: <ANNOTATION_PATH>/instances_val2017.json
          has_background: True
          sort_annotations: True
          use_full_label_map: True
        data_source: <DATA_PATH>/val2017
        preprocessing:
          - type: resize
            aspect_ratio_scale: fit_to_window
            dst_height: 800
            dst_width: 1365
          - type: padding
            dst_height: 800
            dst_width: 1365
            pad_type: right_bottom
        postprocessing:
          - type: faster_rcnn_postprocessing_resize
            dst_height: 800
            dst_width: 1365
        metrics:
          - type: coco_orig_segm_precision
          - type: coco_orig_precision