evaluations:
  - name: mtcnn
    module: custom_evaluators.mtcnn_evaluator.MTCNNEvaluator
    module_config:
      network_info:
        pnet:
          outputs:
            probability_out: prob1
            region_out: conv4-2
          inputs:
            - name: data
              type: INPUT
              layout: NCWH
          preprocessing:
            - type: bgr_to_rgb
            - type: pyramid
              min_size: 10
              factor: 0.79

        rnet:
          outputs:
            probability_out: prob1
            region_out: conv5-2
          inputs:
            - name: data
              type: INPUT
              layout: NCWH
          preprocessing:
            - type: bgr_to_rgb

        onet:
          outputs:
            probability_out: prob1
            region_out: conv6-2
          inputs:
            - name: data
              type: INPUT
              layout: NCWH
          preprocessing:
            - type: bgr_to_rgb

      launchers:
        - framework: dlsdk
          device: CPU

      datasets:
        - name: wider
          data_source: <PATH_TO_DATASET>/WIDER_val/images
            annotation_conversion:
              converter: wider
              annotation_file: <PATH_TO_DATASET>/wider_face_split/wider_face_val_bbx_gt.txt

          postprocessing:
            - type: filter
              apply_to: prediction
              is_empty: True
            - type: filter
              height_range: 60
              apply_to: annotation

          metrics:
            - type: recall
              ignore_difficult: True
              include_boundaries: True
              allow_multiple_matches_per_ignored: True
              distinct_conf: False

            - type: map
              ignore_difficult: True
              include_boundaries: True
              allow_multiple_matches_per_ignored: True
              distinct_conf: False

