models:
  - name: NCF

    launchers:
      - framework: dlsdk
        device: CPU
        adapter: hit_ratio_adapter
        batch: 2048
        inputs:
            - type: INPUT
              value: "u"
              name: embedding/embedding_lookup/placeholder_port_1
            - type: INPUT
              value: "i"
              name: embedding_1/embedding_lookup/placeholder_port_1
            - type: INPUT
              value: "u"
              name: embedding_2/embedding_lookup/placeholder_port_1
            - type: INPUT
              value: "i"
              name: embedding_3/embedding_lookup/placeholder_port_1
        allow_reshape_input: True

    datasets:
      - name: ncf_dataset
        data_source: ncf
        annotation: <EXISTING FOLDER PATH TO STORE ANNOTATION FILES>/ncf_converter.pickle
        dataset_meta: <EXISTING FOLDER PATH TO STORE ANNOTATION FILES>/ncf_converter.json
        annotation_conversion:
            converter: movie_lens_converter
            rating_file: <PATH TO RATING FILE>/ml-20m-test-ratings.csv
            negative_file: <PATH TO NEGATIVE FILE>/ml-20m-test-negative.csv
            users_max_number: 2048
        reader: ncf_data_reader

        metrics:
          - type: hit_ratio
          - type: ndcg
