name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue will be closed in a week because of 9 months of no activity.'
          stale-pr-message: 'This PR will be closed in a week because of 2 weeks of no activity.'
          close-issue-message: 'This issue was closed because it has been stalled for 9 months with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 2 week with no activity.'
          days-before-pr-stale: 14
          days-before-issue-stale: 274
          days-before-close: 7
          ascending: true
          exempt-pr-labels: 'no_stale'
