apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: "minio"
  replicas: 1  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest  # Use the MinIO image and tag you prefer
          args:
            - server
            - /data
          ports:
            - containerPort: 9000  # Port for MinIO
          env:
            - name: MINIO_ACCESS_KEY
              value: your-access-key
            - name: MINIO_SECRET_KEY
              value: your-secret-key
          volumeMounts:
            - name: minio-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: minio-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi  # Adjust the storage size as needed

apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000  # Port to access MinIO
      targetPort: 9000
  type: ClusterIP  # Use ClusterIP for internal access; consider using LoadBalancer or NodePort for external access


