apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13  # Use the PostgreSQL version you prefer
          ports:
            - containerPort: 5432  # PostgreSQL default port
          env:
            - name: POSTGRES_DB
              value: mydb  # Replace 'mydb' with your desired database name
            - name: POSTGRES_USER
              value: myuser  # Replace 'myuser' with your desired username
            - name: POSTGRES_PASSWORD
              value: mypassword  # Replace 'mypassword' with your desired password

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432  # PostgreSQL default port
      targetPort: 5432
  type: ClusterIP  # Use ClusterIP for internal access; consider using LoadBalancer or NodePort for external access

