@startuml
actor flink
spiderman -> minio: 下载数据清洗后保存至minio
spiderman -> db: 下载数据向量化后保存至db

#spiderman -> flink: spiderman下载配置文件定义的链接, 将其发送给flink
#flink -> flink: 处理接收到的文档, 清洗, 去重
#flink -> minio: 将文档保存在minio中
#flink -> nfs: 将文档保存在nfs中
@enduml