@startuml
actor flink
#使用领域数据精调大模型

#训练小模型
spiderman -> flink: spiderman下载配置文件定义的链接, 将其发送给flink
flink -> flink: 处理接收到的文档, 清洗, 去重
flink -> minio: 将文档保存在minio中
flink -> pytorch: flink启动pytorch训练
@enduml