gantt
section spider
    spiderman: active, a1, 2023-11-14, 1d
        spiderman保存下载信息: active, a1, 2023-11-14, 1d
        spiderman将信息发送给flink: active, a1, 2023-11-14, 1d
        spiderman对外提供api或配置文件: active, a2, 2023-11-14, 1d
section data 
    flink: active, a1, 2023-10-29, 3d
        flink处理网页生成json: active, a1, 2023-10-27, 1d
        flink调用api生成摘要: active, a1, 2023-10-27, 1d
    dvc:
    hydra:
    minio:
    nfs:
    db:
    graphdb:
section model
    wenxin+gpt2: active, a2, 2023-11-15, 1d
    gpt2:
section framework
    jupyter:
    pytorch:
    deepspeed:
section analyze
    gen:
        生成单篇文档摘要: active, a1, 2023-10-27, 1d
        生成多篇文档摘要: active, a1, 2023-10-27, 1d
section service
    chartgpt-web:
    report:
        生成文档报告api: active, a1, 2023-11-14, 1d
        生成文档报告: active, a1, 2023-11-14, 1d
    search:
        搜索报告: active, a1, 2023-11-15, 1d
    translate:
section env
    docker-compse: active, a1, 2023-11-14, 1d
    k8s: active, a1, 2023-11-15, 1d
    server: active, a1, 2023-11-15, 1d
    baiduyun:active, a1, 2023-11-16, 1d