apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  labels:
    app: flink
    component: jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: apache/flink:1.14.3  # Use the Flink version you prefer
        ports:
        - containerPort: 6123  # Flink JobManager port
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  labels:
    app: flink
    component: taskmanager
spec:
  replicas: 2  # You can adjust the number of TaskManagers as needed
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: apache/flink:1.14.3  # Use the Flink version you prefer
        ports:
        - containerPort: 6121  # Flink TaskManager port
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager

---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  selector:
    app: flink
    component: jobmanager
  ports:
  - port: 8081  # Flink Web UI port
    targetPort: 8081
  - port: 6123  # Flink JobManager port
    targetPort: 6123

---
apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager
spec:
  selector:
    app: flink
    component: taskmanager
  ports:
  - port: 6121  # Flink TaskManager port
    targetPort: 6121
