#resources:
#  repositories:
#  - repository: testdata
#    type: github
#    endpoint: openvinotoolkit
#    name: openvinotoolkit/testdata
#    ref: master

jobs:
- job: Lin_lohika
  # About 150% of total time
  timeoutInMinutes: '90'

  pool:
    name: LIN_LOHIKA

  variables:
    system.debug: true
#    VSTS_HTTP_RETRY: 5
#    VSTS_HTTP_TIMEOUT: 200
#    BUILD_TYPE: Release
#    REPO_DIR: $(Build.Repository.LocalPath)
#    MODELS_PATH: $(REPO_DIR)/../testdata
#    WORK_DIR: $(Pipeline.Workspace)/_w
#    BUILD_DIR: $(WORK_DIR)/build

  steps:
  - script: git -C ~/work/openvino fetch origin $(Build.SourceBranch)
    displayName: fetch

#  - checkout: self
#    clean: 'true'
#    submodules: 'true'
#    path: openvino

  - checkout: none

  - script: git -C ~/work/openvino checkout -m $(Build.SourceVersion) && git -C ~/work/openvino submodule update --init --recursive
    displayName: checkout

    # Should be after 'Install dependencies' because Git lfs is not installed
#  - checkout: testdata
#    clean: 'true'
#    submodules: 'true'
#    lfs: 'true'
#    path: testdata

  - script: env -C ~/work ./configreleasenolto.sh
    displayName: CMake

#  - task: CMake@1
#    inputs:
#      # CMake must get Python 3.x version by default
#      cmakeArgs: >
#        -GNinja
#        -DENABLE_CPPLINT=OFF
#        -DCMAKE_VERBOSE_MAKEFILE=ON
#        -DCMAKE_BUILD_TYPE=$(BUILD_TYPE)
#        -DENABLE_PYTHON=ON
#        -DPYTHON_EXECUTABLE=/usr/bin/python3.8
#        -DENABLE_TESTS=ON
#        -DENABLE_OV_ONNX_FRONTEND=ON
#        -DENABLE_FASTER_BUILD=ON
#        -DENABLE_STRICT_DEPENDENCIES=OFF
#        -DOPENVINO_EXTRA_MODULES=$(OPENVINO_CONTRIB_REPO_DIR)/modules
#        -S $(REPO_DIR)
#        -B $(BUILD_DIR)

  - script: |
      env -C ~/work
      ./buildreleasenolto.sh
      libopenvino_gapi_preproc.so
      openvino_intel_cpu_plugin
      openvino_intel_gpu_plugin
      ov_gpu_unit_tests
      gpuFuncTests
    displayName: Build Lin

  - script: ~/work/testreleasenolto.sh
    displayName: cldnn tests
